### ISSUE TITLE
CasparCG Technical Steering Committee (TSC) Meeting 2020-05-28

### ISSUE THREAD

**Issue by dotarmin** [CasparCG/TSC#1]
### When
Thu, 28 May 2020 at 14:00 UTC

| Timezone  	| Date/Time                    	 |
|-----------	|------------------------------- |
| London    	| Thu, 28 May 2020 at 15:00 BST  |
| Stockholm 	| Thu, 28 May 2020 at 16:00 CEST |

> *You can also find your local time by following the link: [check my local time][1]*

### Where
Google Meet, a link will be sent to attendes prior to the meeting.

---
### Agenda
The agenda will be formed prior to the meeting and will consist of issues and pull requests from the CasparCG organization with the **tsc-agenda** label. Comments posted on this issue will also be a part of the agenda.

#### CasparCG/Server
* mpegts seeking broken CasparCG/server#1304
* SET 1 MODE is out of order CasparCG/server#1303
* Warning when using 1080p50 CasparCG/server#1299
* Add Support for Kronos K8 card type, and bug fixes CasparCG/server#1302 (PR)
* Review and discuss milestone v2.3.0 LTS

#### **CasparCG/Project**
* Announcement repository
* TSC repository

---
### Invited
* Armin Hafizovic (@dotarmin) — TSC
* Jesper Stærkær (@jesperstarkar) — TSC
* Julian Waller (@Julusian) — TSC
* Olle Soprani (@5opr4ni) — TSC
* Robert Nagy (@ronag) - TSC

### Guests
In the future we will be able to invite guests and observers, but we have to form the processes around the technical steering committee first before we can invite others to participate.

---
### Notes
The agenda is formed by issues and pull requests labelled with tsc-agenda across all of the repositories in the CasparCG organization. Please label any additional issues or pull requests that we need to bring up for discussion before the meeting starts.

[1]: https://www.timeanddate.com/worldclock/fixedtime.html?msg=CasparCG+Technical+Steering+Committee+Meeting+%28Thu%2C+28+May+2020%29&iso=20200528T14&p1=1440&ah=1

**Comment by jesperstarkar** [comment]
- Safe-guarding and/or protocol logic to prevent invalid opearations on routes https://github.com/CasparCG/server/issues/1295

**Comment by dotarmin** [comment]
Meeting has been moved to happen today. Issue is updated with new date and time.
